No user settings database specified. Ignoring.

Welcome to Granota launcher. Loading modules...




36 registered modules,
0 unloaded modules


Connecting to irc.autie.net:6667...
Connected.
Traceback (most recent call last):
  File "/home/roc/Documents/Python/Granota/willie/bot.py", line 674, in call
    exit_code = func(willie, trigger)
  File "/home/roc/Documents/Python/Granota/willie/modules/custom_msgs.py", line 33, in custom_show
    msg = correct.split("||||")[1]
UnboundLocalError: local variable 'correct' referenced before assignment

Traceback (most recent call last):
  File "/home/roc/Documents/Python/Granota/willie/bot.py", line 674, in call
    exit_code = func(willie, trigger)
  File "/home/roc/Documents/Python/Granota/willie/modules/custom_msgs.py", line 34, in custom_show
    bot.say(msg)
UnboundLocalError: local variable 'msg' referenced before assignment

Traceback (most recent call last):
  File "/home/roc/Documents/Python/Granota/willie/bot.py", line 674, in call
    exit_code = func(willie, trigger)
  File "/home/roc/Documents/Python/Granota/willie/modules/custom_msgs.py", line 12, in custom
    key = trigger.group(3).split()[1]
IndexError: list index out of range

Traceback (most recent call last):
  File "/home/roc/Documents/Python/Granota/willie/bot.py", line 674, in call
    exit_code = func(willie, trigger)
  File "/home/roc/Documents/Python/Granota/willie/modules/custom_msgs.py", line 12, in custom
    key = trigger.group(3).split()[1]
IndexError: list index out of range

